---
title: "HAB_Cyano"
output: html_document
date: "2024-03-07"
---
#Library

```{r}
library(tidyverse)
library(googlesheets4)
library(oce)
library(padr)
library(rEDM)
library(ggplot2)
library(zoo)

```

```{r}
#Charles River
#Reads data into R
CR2023 <- read_sheet('https://docs.google.com/spreadsheets/d/1R_HdqGuVMlfRyVPCzOw3CvbOjXDQfzFtDCMvKdj5vXU/edit?usp=sharing')

CR2022 <- read_sheet('https://docs.google.com/spreadsheets/d/1equdXHt4d-2s3r8YSsuHfpLufeRmGqno-SJqhcEwuNY/edit?usp=sharing')

CR2021 <- read_sheet('https://docs.google.com/spreadsheets/d/1CBzAD9uot_SPkY-JV-lJB6FSxSjlgXIS8A4jSY9SJjE/edit?usp=sharing')

CR2020 <- read_sheet('https://docs.google.com/spreadsheets/d/1fOV7JfJwLxddCaTsR0vkUodOZup4Y6HwVthMLzexe-I/edit?usp=sharing')

CR2019 <- read_sheet('https://docs.google.com/spreadsheets/d/1WGTUQ7F8wadO4RJ6PsfRsEnvwqNMdnAsdX71xqI9L-4/edit?usp=sharing')

CR2018 <- read_sheet('https://docs.google.com/spreadsheets/d/17AX8HNLXUCYz6YJIHRnb_rrKuzDudyAEq5WEhbSxOFQ/edit?usp=sharing')

CR2017 <- read_sheet('https://docs.google.com/spreadsheets/d/18xDJ9cLaZuj3JqhFsf847nSLMGKjfvWZmHWifsrPBq8/edit?usp=sharing')

CR2016 <- read_sheet('https://docs.google.com/spreadsheets/d/1rEOGM2H9cgVbFgVkIQZjIyzzl03fIywtkxBNg7GmXrY/edit?usp=sharing')

CR2015 <- read_sheet('https://docs.google.com/spreadsheets/d/11I8RQnOgZ9xmVEpaTVM_ELQZdTTp6T_305nwxkNI92I/edit?usp=sharing')

#Prints the data
```


```{r}
#bind rows
df_CR <- bind_rows(
  CR2015,
  CR2016,
  CR2017, 
  CR2018,
  CR2019,
  CR2020,
  CR2021,
  CR2022,
  CR2023
)
#combine data
df_CR <- df_CR %>%
  mutate(hour = pmin(hour(`time est`),hour(`time edt`),na.rm=T),
         minute = pmin(minute(`time est`),minute(`time edt`),na.rm=T)) %>%
  select(date,hour,minute,chl=`chlorophyll (rfu)`,phy=`phycocyanin (rfu)`, ph=`ph`, Celsius =`temp c`,  spcond = `spcond (ms/cm)`, do = `do (mg/l)`,turb = `turbidity (fnu)` )
  
#%>% rename(`time est`=time)

```


#Aggregate Values Daily
```{r}
df_CR$Salinity <- 

  swSCTp(
  df_CR$spcond,
df_CR$Celsius,
  pressure = rep(10.1325,NROW(df_CR)),
  # "mS/cm",
"",
  eos = getOption("oceEOS", default = "gsw")
)


ag_df_CR <-df_CR %>%
   group_by(date) %>%
  summarise(chl=mean(chl), phy=mean(phy), ph=mean(ph), Celsius=mean(Celsius), spcond=mean(spcond), do=mean(do), turb=mean(turb), Salinity = mean(Salinity))

```

### First Diff Phy

```{r}
ag_df_CR <- ag_df_CR %>% pad %>%
mutate(del_phy = phy - lag(phy,1))
 ag_df_CR %>% ggplot(aes(x=date,y=del_phy)) + geom_line()

```


#CYANO COUNTS

```{r}

MDPH <- read_sheet('https://docs.google.com/spreadsheets/d/1HeVNoOE7Z_eYGcaoJxT9GQlHMzJcTPW8jMsImqoyCRw/edit?usp=sharing')

MDPH2020 <- read_sheet('https://docs.google.com/spreadsheets/d/1HeVNoOE7Z_eYGcaoJxT9GQlHMzJcTPW8jMsImqoyCRw/edit?usp=sharing', sheet = 2)

MDPH2022 <- read_sheet('https://docs.google.com/spreadsheets/d/1HeVNoOE7Z_eYGcaoJxT9GQlHMzJcTPW8jMsImqoyCRw/edit?usp=sharing', sheet = 3)

MaxPaper20152019 <-  read_sheet('https://docs.google.com/spreadsheets/d/1K0FwgETetaCSKT7jng0CzTzppFn3p7Q3QiKy8oqbZnc/edit?usp=sharing')


```

```{r}


# Subset columns "Site_ID", "Date", and "Cyanobacteria (cells/mL)" from each data frame
MaxPaper20152019_subset <- MaxPaper20152019[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]
MDPH_subset <- MDPH[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]
MDPH2020_subset <- MDPH2020[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]
MDPH2022_subset <- MDPH2022[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]


# Columns to exclude from conversion
exclude_cols <- c("Date", "Site_ID")

 #Convert numeric columns (excluding "Date" and "Site_ID")
MDPH_subset <- MDPH_subset %>%
  mutate_at(vars(-one_of(exclude_cols)), ~ as.numeric(as.character(.)))

MDPH2022_subset <- MDPH2022_subset %>%
  mutate_at(vars(-one_of(exclude_cols)), ~ as.numeric(as.character(.)))

MDPH2020_subset <- MDPH2020_subset %>%
  mutate_at(vars(-one_of(exclude_cols)), ~ as.numeric(as.character(.)))

MaxPaper20152019_subset <- MaxPaper20152019_subset %>%
  mutate_at(vars(-one_of(exclude_cols)), ~ as.numeric(as.character(.)))

# Bind rows from the subsetted data frames
All.Cyano <- bind_rows(MaxPaper20152019_subset, MDPH_subset, MDPH2020_subset, MDPH2022_subset)


```


```{r}

#omit

All.Cyano <- na.omit(All.Cyano)

#combine data
ag_All.Cyano <- All.cyano %>%
group_by(Date) %>%
  summarise(Site_ID = Site_ID, Cyanobacteria (cells/mL) = mean(Cyanobacteria (cells/mL)))

ag_All.Cyano <- All.Cyano %>%
  group_by(Date) %>%
  summarise(Site_ID = first(Site_ID), `Cyanobacteria (cells/mL)` = mean(`Cyanobacteria (cells/mL)`, na.rm = TRUE))

```



#CRWA Cyano Counts 
```{r}
https://docs.google.com/spreadsheets/d/1P8_Tv6YnqysdLAwesoREWUTKg1T8-97k5a46wRz79u0/edit?usp=sharing

```
 
#Previous CRWA CODE

```{r}


 # do something about Results that are "<10.0". turn into 0 for now?

#CRWAdata <- CRWAdata %>%
  #mutate( = ifelse(Value == "<10.0", 0, as.numeric(Value)))

CRWAdata_wide <- CRWAdata %>%
  select(Site_ID,Date_Collected,
         Time_Collected,Component_ID,Reporting_Result) %>%
  group_by(Site_ID,Date_Collected,Time_Collected,Component_ID) %>%
  summarise(Reporting_Result = mean(Reporting_Result,na.rm=T),.groups = "keep") %>%
  pivot_wider(names_from= Component_ID,values_from=Reporting_Result)


#Data types
CRWAtypes <- CRWAdata %>% distinct(CRWAdata$Component_ID) #remove duplicate data
Component_ID2 <- CRWAtypes

```


```{r}
#SITE IDs
CRWAMap_stations <- read_sheet('https://docs.google.com/spreadsheets/d/1mkNv-07loU1pDz8SWE0spoa-phkgEL65I69Hi26P3Rc/edit?usp=sharing')
CRWAMap_stations <- CRWAMap_stations[-c(2,6:23)] #remove columns


```

```{r}
#Combine DFs
CRWAfinal <-  
right_join(CRWAdata_wide , CRWAMap_stations,  by = c("Site_ID"  = "Site_ID"))

write.csv(CRWAfinal, file = "CRWAfinal.csv")
```


#EPA Cyano Counts 

```{r}

CyanoEPA2015.1 <- read_sheet('https://docs.google.com/spreadsheets/d/1YjTl7x6zHcui_U961o0Kez5URcWhF2uYE6QHGnK1Sy0/edit?usp=sharing')


CyanoEPA2015.2 <- read_sheet('https://docs.google.com/spreadsheets/d/1nE4dxDyJYQCrRyeFfUY9ogNmjagzCA8mHnZlUCm5DxY/edit?usp=sharing')


CyanoEPA2016 <- read_sheet('https://docs.google.com/spreadsheets/d/1va3luWGR-wbgF6peO5kFiGG3Eg9Fleo2bu3edjQmR_s/edit?usp=sharing')


CyanoEPA2017 <- read_sheet('https://docs.google.com/spreadsheets/d/100ac4ZqGQpqpvcEuHzxfOX97lCt4lGz_eGdpo3K0vfU/edit?usp=sharing')


CyanoEPA2019 <- read_sheet('https://docs.google.com/spreadsheets/d/1RJ_FSBPtUrrxPRLI1G8IDwtaHq3jyrfoXuDTLBJr8Kg/edit?usp=sharing')

CyanoEPA2021 <- read_sheet('https://docs.google.com/spreadsheets/d/1B3Aeg-TlOdLnrAinK7D2KTKvTCtiM2KRMK9Tx8wYz3Q/edit?usp=sharing')


CyanoEPA2022 <- read_sheet('https://docs.google.com/spreadsheets/d/1q7xMi6thpArfeoH-xV3QAPg2_7nhTatp3BZ6cb8g4NQ/edit?usp=sharing')

CyanoEPA2015.1_subset <- CyanoEPA2015.1[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]
CyanoEPA2015.2_subset  <- CyanoEPA2015.2[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]
CyanoEPA2016_subset <- CyanoEPA2016[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]
CyanoEPA2017_subset <- CyanoEPA2017[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]
CyanoEPA2019_subset <- CyanoEPA2019[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]
CyanoEPA2021_subset <- CyanoEPA2021[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]
CyanoEPA2022_subset <- CyanoEPA2022[, c("Site_ID", "Date", "Cyanobacteria (cells/mL)")]


MaxPaper20152019_subset$Date <- as.Date(MaxPaper20152019_subset$Date)
MDPH_subset$Date <- as.Date(MDPH_subset$Date)
MDPH2020_subset$Date <- as.Date(MDPH2020_subset$Date)
MDPH2022_subset$Date <- as.Date(MDPH2022_subset$Date)
CyanoEPA2015.1_subset$Date <- as.Date(CyanoEPA2015.1_subset$Date, format = "%m/%d/%Y")
CyanoEPA2015.2_subset$Date <- as.Date(CyanoEPA2015.2_subset$Date, format = "%m/%d/%Y")
CyanoEPA2016_subset$Date <- as.Date(CyanoEPA2016_subset$Date, format = "%m/%d/%Y")
CyanoEPA2017_subset$Date <- as.Date(CyanoEPA2017_subset$Date, format = "%m/%d/%Y")
CyanoEPA2019_subset$Date <- as.Date(CyanoEPA2019_subset$Date, format = "%m/%d/%Y")
CyanoEPA2021_subset$Date <- as.Date(CyanoEPA2021_subset$Date, format = "%m/%d/%Y")
CyanoEPA2022_subset$Date <- as.Date(CyanoEPA2022_subset$Date, format = "%m/%d/%Y")

All.Cyano <- bind_rows(MaxPaper20152019_subset, MDPH_subset, MDPH2020_subset, MDPH2022_subset, CyanoEPA2015.1_subset, CyanoEPA2015.2_subset, CyanoEPA2016_subset, CyanoEPA2017_subset, CyanoEPA2019_subset,  CyanoEPA2021_subset, CyanoEPA2022_subset )




```











#PLOTS

#PAD CR 

```{r}
ag_df_CR <- ag_df_CR %>% pad()

```

#Plot

#2015
```{r}

# Convert "Date" to proper date format
ag_df_CR$date <- as.Date(ag_df_CR$date)

ag_df_CR <- ag_df_CR %>% pad()



All.Cyano %>%
  group_by(Date) %>%
  filter(year(Date) == 2015) %>%
  ggplot(aes(x = Date, y = `Cyanobacteria (cells/mL)`, color = Site_ID)) +
  geom_point() +
  labs(title = "2015 Cyano")

All.Cyano %>%
  group_by(Date) %>%
  filter(year(Date) == 2016) %>%
  ggplot(aes(x = Date, y = `Cyanobacteria (cells/mL)`, color = Site_ID)) +
  geom_point() +
  labs(title = "2016 Cyano")


All.Cyano %>%
  group_by(Date) %>%
  filter(year(Date) == 2017) %>%
  ggplot(aes(x = Date, y = `Cyanobacteria (cells/mL)`, color = Site_ID)) +
  geom_point()+
  labs(title = "2017 Cyano")

All.Cyano %>%
  group_by(Date) %>%
  filter(year(Date) == 2018) %>%
  ggplot(aes(x = Date, y = `Cyanobacteria (cells/mL)`, color = Site_ID)) +
  geom_point()+
  labs(title = "2018 Cyano")


All.Cyano %>%
  group_by(Date) %>%
  filter(year(Date) == 2019) %>%
  ggplot(aes(x = Date, y = `Cyanobacteria (cells/mL)`, color = Site_ID)) +
  geom_point()+
  labs(title = "2019 Cyano")


All.Cyano %>%
  group_by(Date) %>%
  filter(year(Date) == 2020) %>%
  ggplot(aes(x = Date, y = `Cyanobacteria (cells/mL)`, color = Site_ID)) +
  geom_point()+
  labs(title = "2020 Cyano")



All.Cyano %>%
  group_by(Date) %>%
  filter(year(Date) == 2021) %>%
  ggplot(aes(x = Date, y = `Cyanobacteria (cells/mL)`, color = Site_ID)) +
  geom_point()+
  labs(title = "2021 Cyano")



All.Cyano %>%
  group_by(Date) %>%
  filter(year(Date) == 2022) %>%
  ggplot(aes(x = Date, y = `Cyanobacteria (cells/mL)`, color = Site_ID)) +
  geom_point()+
  labs(title = "2022 Cyano")




#2015
##PHY
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2015-05-10", "2015-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "orange", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2015 PHY")

#CHL
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2015-05-10", "2015-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "green", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2015 CHL")

#2016
##PHY
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2016-05-10", "2016-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "orange", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2016 PHY")

#CHL
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2016-05-10", "2016-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "green", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2016 CHL")


#2017
##PHY
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2017-05-10", "2016-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "orange", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2017 PHY")

#CHL
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2017-05-10", "2017-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "green", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2017 CHL")


#2018
##PHY
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2018-05-10", "2018-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "orange", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2018 PHY")

#CHL
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2018-05-10", "2018-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "green", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2018 CHL")


#2019
##PHY
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2019-05-10", "2019-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "orange", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2019 PHY")

#CHL
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2019-05-10", "2019-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "green", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2019 CHL")



#2020
##PHY
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2020-05-10", "2020-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "orange", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2020 PHY")

#CHL
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2020-05-10", "2020-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "green", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2020 CHL")




#2021
##PHY
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2021-05-10", "2021-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "orange", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2021 PHY")

#CHL
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2021-05-10", "2021-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "green", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2021 CHL")




#2022
##PHY
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2022-05-10", "2022-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "orange", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2022 PHY")

#CHL
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2022-05-10", "2022-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "green", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2022 CHL")



#2023
##PHY
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2023-05-10", "2023-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "orange", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2023 PHY")

#CHL
ggplot(ag_df_CR, aes(x = date, y = phy, color = "line")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +  # Show all months on the x-axis
  coord_cartesian(xlim = as.Date(c("2023-05-10", "2023-10-25"))) +  # Set x-axis limits
  scale_color_manual(values = "green", labels = "phy") + # Specify the color and label for the legend
    labs(title = "2023 CHL")






```

divide by std dev 



```{r}






#WEEKS
# Plot ag_df_CR
ggplot(ag_df_CR, aes(x = date, y = phy, color = "phy")) + 
  geom_path() +
  scale_x_date(date_breaks = "1 week", date_labels = "%W") +  # Show all weeks on the x-axis
  coord_cartesian(xlim = as.Date(c("2015-05-01", "2015-11-30")))  # Set x-axis limits




# Plot ag_df_CR
ggplot(ag_df_CR_2015, aes(x = date, y = phy, color = "phy")) + 
  geom_path() +
  # Add points from ag_All.Cyano
  geom_point(data = ag_All.Cyano_2015, aes(x = Date, y = `Cyanobacteria (cells/mL)` / 1000000, color = Site_ID)) +
  labs(color = "Data", y = "Cyanobacteria (cells/mL) (x10^-3)") +  # Customize legend title and y-axis label
  scale_y_continuous(labels = scales::scientific_format(10^-3))  # Set y-axis labels as scientific notation

#CHL
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2015) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl"))


```






#2016
```{r}
#PHY
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2016) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=phy,color="phy"))

#CHL
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2016) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl"))


```

#2017
```{r}
#PHY
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2017) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=phy,color="phy"))

#CHL
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2017) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl"))


```

#2018
```{r}
#PHY
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2018) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=phy,color="phy"))

#CHL
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2018) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl"))


```

#2019
```{r}
#PHY
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2019) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=phy,color="phy"))

#CHL
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2019) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl"))


```


#2020
```{r}
#PHY
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2020) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=phy,color="phy"))

#CHL
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2020) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl"))


```
 

#2021
```{r}
#PHY
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2021) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=phy,color="phy"))

#CHL
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2021) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl"))


```
 
#2022
```{r}
#PHY
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2022) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=phy,color="phy"))

#CHL
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2022) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl"))


```


#2023
```{r}
#PHY
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2023) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=phy,color="phy"))

#CHL
ag_df_CR %>% group_by(date) %>%
  filter(year(date) == 2023) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl"))


```











