---
title: "Updated_EPABUOY"
output: html_document
date: "2024-03-01"
editor_options: 
  chunk_output_type: console
---
```{r}
library(rEDM)
library(tidyverse)
library(googlesheets4)
library(padr)
library(oce)
library(tseries)
library(forecast)
library(spatstat)
library(tseries)
library(corrplot)
library(lubridate)
library(psych)
library(Hmisc)
```



```{r}
#Charles River
#Reads data into R
#DID NOT RECIEVE YET 
CR2023 <- read_sheet('https://docs.google.com/spreadsheets/d/1sMKGzW71qErP8DIrxWDvlgqN3o9MrprLjjAFGsOie3I/edit?usp=sharing')

CR2022 <- read_sheet('https://docs.google.com/spreadsheets/d/1F5l-1dWi7EFOaEKf9o3eUBi6BgQOrC1Rj_lVNRPrx5U/edit?usp=sharing', sheet = 2)

CR2021 <- read_sheet('https://docs.google.com/spreadsheets/d/1vaDoymaAQmNFKqIgo1LStI7GQSKDeIqLy7We85IA3Oo/edit?usp=sharing', sheet = 2)

CR2020 <- read_sheet('https://docs.google.com/spreadsheets/d/1Qvt0PIK4wPFPKbkM98pSQp9TbPsu_a6frTWFKv3aNQ4/edit?usp=sharing', sheet = 2)

CR2019 <- read_sheet('https://docs.google.com/spreadsheets/d/1PGZCChA-8HU-cLvPSxqrxd89gLTletDYgogMGwv4Dg4/edit?usp=sharing', sheet = 2)

CR2018 <- read_sheet('https://docs.google.com/spreadsheets/d/1CO0DHuKb3C-hE9z-r5yR-SXwPnZWZg4vQDuEtRv2r7k/edit?usp=sharing', sheet = 2)

CR2017 <- read_sheet('https://docs.google.com/spreadsheets/d/11SO-RxRhcc4qqn3gRt4n13JWClFoG--kISMoPAR2FRA/edit?usp=sharing', sheet = 2)

CR2016 <- read_sheet('https://docs.google.com/spreadsheets/d/1sMcEOIzxPTUZ93-pTJBE0lQ3SI8kKihLZRdpZ32_Lyw/edit?usp=sharing', sheet = 2)

CR2015 <- read_sheet('https://docs.google.com/spreadsheets/d/1t5joquxku9OfQGDdsabp-GdR2sUw8hPDcwatC3SL90Q/edit?usp=sharing', sheet = 2)

#Prints the data
```



```{r}

#CR2023

if (file.exists("CR2023.rds")) {
  # If it's saved locally, load the data
  CR2023 <- readRDS("CR2023.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
CR2023 <- read_sheet('https://docs.google.com/spreadsheets/d/1sMKGzW71qErP8DIrxWDvlgqN3o9MrprLjjAFGsOie3I/edit?usp=sharing')
  saveRDS(CR2023, "CR2023.rds")
}

#CR2022

if (file.exists("CR2022.rds")) {
  # If it's saved locally, load the data
  CR2022 <- readRDS("CR2022.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
CR2022 <- read_sheet('https://docs.google.com/spreadsheets/d/1F5l-1dWi7EFOaEKf9o3eUBi6BgQOrC1Rj_lVNRPrx5U/edit?usp=sharing', sheet = 2)
  saveRDS(CR2022, "CR2022.rds")
}

#CR2021

if (file.exists("CR2021.rds")) {
  # If it's saved locally, load the data
  CR2021 <- readRDS("CR2021.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
CR2021 <- read_sheet('https://docs.google.com/spreadsheets/d/1vaDoymaAQmNFKqIgo1LStI7GQSKDeIqLy7We85IA3Oo/edit?usp=sharing', sheet = 2)
  saveRDS(CR2021, "CR2021.rds")
}


#CR2020


if (file.exists("CR2020.rds")) {
  # If it's saved locally, load the data
  CR2020 <- readRDS("CR2020.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
CR2020 <- read_sheet('https://docs.google.com/spreadsheets/d/1Qvt0PIK4wPFPKbkM98pSQp9TbPsu_a6frTWFKv3aNQ4/edit?usp=sharing', sheet = 2)
  saveRDS(CR2020, "CR2020.rds")
}


#CR2019

if (file.exists("CR2019.rds")) {
  # If it's saved locally, load the data
  CR2019 <- readRDS("CR2019.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
CR2019 <- read_sheet('https://docs.google.com/spreadsheets/d/1PGZCChA-8HU-cLvPSxqrxd89gLTletDYgogMGwv4Dg4/edit?usp=sharing', sheet = 2)
  saveRDS(CR2019, "CR2019.rds")
}


#CR2018


if (file.exists("CR2018.rds")) {
  # If it's saved locally, load the data
  CR2018 <- readRDS("CR2018.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
CR2018 <- read_sheet('https://docs.google.com/spreadsheets/d/1CO0DHuKb3C-hE9z-r5yR-SXwPnZWZg4vQDuEtRv2r7k/edit?usp=sharing', sheet = 2)
  saveRDS(CR2018, "CR2018.rds")
}


#CR2017

if (file.exists("CR2017.rds")) {
  # If it's saved locally, load the data
  CR2017 <- readRDS("CR2018.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
CR2017 <- read_sheet('https://docs.google.com/spreadsheets/d/11SO-RxRhcc4qqn3gRt4n13JWClFoG--kISMoPAR2FRA/edit?usp=sharing', sheet = 2)
  saveRDS(CR2017, "CR2017.rds")
}

#CR2016


if (file.exists("CR2016.rds")) {
  # If it's saved locally, load the data
  CR2016 <- readRDS("CR2016.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
CR2016 <- read_sheet('https://docs.google.com/spreadsheets/d/1sMcEOIzxPTUZ93-pTJBE0lQ3SI8kKihLZRdpZ32_Lyw/edit?usp=sharing', sheet = 2)
  saveRDS(CR2017, "CR2016.rds")
}


#CR2015

if (file.exists("CR2015.rds")) {
  # If it's saved locally, load the data
  CR2015 <- readRDS("CR2015.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
CR2015 <- read_sheet('https://docs.google.com/spreadsheets/d/1t5joquxku9OfQGDdsabp-GdR2sUw8hPDcwatC3SL90Q/edit?usp=sharing', sheet = 2)
  saveRDS(CR2015, "CR2015.rds")
}


```






```{r}
#bind rows

CR2021$date <- as.Date(CR2021$datetime)


df_CR <- bind_rows(
  CR2015,
  CR2016,
  CR2017, 
  CR2018,
  CR2019,
  CR2020,
  CR2021,
  CR2022,
  CR2023, 
)
#combine data
df_CR <- df_CR %>%
  mutate(hour = pmin(hour(`time est`),hour(`time edt`),na.rm=T),
         minute = pmin(minute(`time est`),minute(`time edt`),na.rm=T)) %>%
  select(date,hour,minute,chl=`chlorophyll (rfu)`,phy=`phycocyanin (rfu)`, ph=`ph`, Celsius =`temp c`,  spcond = `spcond (ms/cm)`, do = `do (mg/l)`,turb = `turbidity (fnu)` )
  
#%>% rename(`time est`=time)

```

### Convert to Salinity

```{r}

df_CR$Salinity <- 

  swSCTp(
  df_CR$spcond,
df_CR$Celsius,
  pressure = rep(10.1325,NROW(df_CR)),
  # "mS/cm",
"",
  eos = getOption("oceEOS", default = "gsw")
)

```

# Non-Aggregated Values

## Visualize 2021 Salinity + Chl

```{r}
#Visualize Salinity 2021 

df_CR %>%
  mutate(date = as.Date(date)) %>%
  group_by(date) %>%
  filter(date >= as.Date("2021-05-01") & date <= as.Date("2021-11-01"))  %>%
  ggplot(aes(x = date)) + 
  geom_path(aes(y = Salinity, color = "Salinity")) +
  scale_x_date(date_labels = "%b", date_breaks = "1 month") +
  ggtitle("Salinity 2021") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Month", y = "Salinity (ppm)")

#Visualize Chl 2021 

df_CR %>%
  mutate(date = as.Date(date)) %>%
  group_by(date) %>%
  filter(date >= as.Date("2021-05-01") & date <= as.Date("2021-11-01"))  %>%
  ggplot(aes(x = date)) + 
  geom_path(aes(y = chl, color = "chl")) +
  scale_x_date(date_labels = "%b", date_breaks = "1 month") +
  ggtitle("Chlorophyll 2021") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Month", y = "Chlorophyll (RFU)")
  

#Visualize Phy 2021 

df_CR %>%
  mutate(date = as.Date(date)) %>%
  group_by(date) %>%
  filter(date >= as.Date("2021-05-01") & date <= as.Date("2021-11-01"))  %>%
  ggplot(aes(x = date)) + 
  geom_path(aes(y = chl, color = "phy")) +
  scale_x_date(date_labels = "%b", date_breaks = "1 month") +
  ggtitle("Phycocanin 2021") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Month", y = "Phycocanin (RFU)")
```

#add rows w/ missing NA values

```{r}

df_CR <- df_CR %>% pad()

```

### Plot Chl + Phy

```{r}

df_CR %>% group_by(date,hour) %>%
    filter(year(date) >= 2021) %>%
  summarise(across(c("chl","phy"),mean),.groups="keep") %>%
  mutate(date= date+hours(hour)) %>%
  ggplot(aes(x=date)) + 
  geom_path(aes(y=chl,color="chl")) + 
  geom_path(aes(y=phy,color="phy")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle(" < 2021 Chlorophyll V. Phycocanin ") + 
    labs(x = "Dates", y = "RFU")


```

### Plot \> 2021 EPA Buoy Vars

```{r}


df_CR %>%
  group_by(date, hour) %>%
  filter(year(date) >= 2021) %>%
  summarise(across(c("chl", "phy", "ph", "Celsius", "spcond", "do", "turb", "Salinity"), mean), .groups = "keep") %>%
  mutate(date = date + hours(hour)) %>%
  ggplot(aes(x = date)) +
  geom_path(aes(y = chl, color = "Chlorophyll (RFU)")) +
  geom_path(aes(y = phy, color = "Phycocanin (RFU)")) +
  geom_path(aes(y = ph, color = "pH")) +
  geom_path(aes(y = Celsius, color = "Temperature (Celsius)")) +
  geom_path(aes(y = spcond, color = "Specific Conductance Ratio (mS/cm)")) +
  geom_path(aes(y = do, color = "Dissolved Oxygen (mg/L)")) +
  geom_path(aes(y = turb, color = "Turbidity (FNU)")) +
  geom_path(aes(y = Salinity, color = "Salinity (ppm)")) +
  scale_color_manual(
    values = c("Chlorophyll (RFU)" = "green",
               "Phycocanin (RFU)" = "orange",
               "pH" = "brown",
               "Temperature (Celsius)" = "red",
               "Specific Conductance Ratio (mS/cm)" = "pink",
               "Dissolved Oxygen (mg/L)" = "yellow",
               "Turbidity (FNU)" = "purple",  # Removed the extra space here
               "Salinity (ppm)" = "blue"),
    name = "Color"
  ) + 
  labs(x = "Dates", y = "Units") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle(" < 2021 All EPA Buoy Variables")

```

```{r}

#without salinity
df_CR %>%
  group_by(date, hour) %>%
  filter(year(date) >= 2021) %>%
  summarise(across(c("chl", "phy", "ph", "Celsius", "spcond", "do", "turb"), mean), .groups = "keep") %>%
  mutate(date = date + hours(hour)) %>%
  ggplot(aes(x = date)) +
  geom_path(aes(y = chl, color = "Chlorophyll (RFU)")) +
  geom_path(aes(y = phy, color = "Phycocanin (RFU)")) +
  geom_path(aes(y = ph, color = "pH")) +
  geom_path(aes(y = Celsius, color = "Temperature (Celsius)")) +
  geom_path(aes(y = spcond, color = "Specific Conductance Ratio (mS/cm)")) +
  geom_path(aes(y = do, color = "Dissolved Oxygen (mg/L)")) +
  geom_path(aes(y = turb, color = "Turbidity (FNU)")) +
  scale_color_manual(
    values = c("Chlorophyll (RFU)" = "green",
               "Phycocanin (RFU)" = "orange",
               "pH" = "brown",
               "Temperature (Celsius)" = "red",
               "Specific Conductance Ratio (mS/cm)" = "pink",
               "Dissolved Oxygen (mg/L)" = "yellow",
               "Turbidity (FNU)" = "purple",
    name = "Color"
  ) + 
  labs(x = "Dates", y = "Units") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle(" < 2021 All EPA Buoy Variables")
```

### Plot All EPA Buoy Vars All Time

```{r}
df_CR %>%
  group_by(date, hour) %>%
  summarise(across(c("chl", "phy", "ph", "Celsius", "spcond", "do", "Salinity"), mean), .groups = "keep") %>%
  mutate(date = date + hours(hour)) %>%
  ggplot(aes(x = date)) +
  geom_path(aes(y = chl, color = "Chlorophyll (RFU)")) +
  geom_path(aes(y = phy, color = "Phycocanin (RFU)")) +
  geom_path(aes(y = ph, color = "pH")) +
  geom_path(aes(y = Celsius, color = "Temperature (Celsius)")) +
  geom_path(aes(y = spcond, color = "Specific Conductance Ratio (mS/cm)")) +
  geom_path(aes(y = do, color = "Dissolved Oxygen (mg/L)")) +
  geom_path(aes(y = Salinity, color = "Salinity (ppm)")) +
  scale_color_manual(
    values = c("Chlorophyll (RFU)" = "green",
               "Phycocanin (RFU)" = "orange",
               "pH" = "brown",
               "Temperature (Celsius)" = "red",
               "Specific Conductance Ratio (mS/cm)" = "pink",
               "Dissolved Oxygen (mg/L)" = "yellow",
               "Turbidity (FNU)" = "purple",
               "Salinity (ppm)" = "blue"),
    name = "Color"
  ) + 
      labs(x = "Dates", y = "Units") +
theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("All EPA Buoy Vars")
```


